#
# This source file is part of the OpenTSLM open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University, ETH Zurich, and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

dirs:
  - .
useGitIgnore: true
ignorePatterns:
  - pattern: "doc:/"
  - pattern: "http://localhost"
  - pattern: "https://doi.org"
